services:
  db:
    image: postgres:15-alpine
    env_file: .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_prod:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on: [db]
    env_file: .env.production
    restart: unless-stopped
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf

volumes:
  db_prod:
