{
    "name": "Mumtaz Lead Nurture",
    "version": "19.0.1.0.0",
    "summary": "Lead nurturing, qualification, and auto-conversion engine for Odoo ERP sales",
    "category": "Sales/CRM",
    "author": "Mumtaz Digital",
    "website": "https://mumtaz.digital",
    "license": "LGPL-3",
    "depends": ["crm", "mail", "mumtaz_lead_scraper"],
    "data": [
        "security/lead_nurture_security.xml",
        "security/ir.model.access.csv",
        "data/lead_nurture_data.xml",
        "data/lead_nurture_cron.xml",
        "views/lead_nurture_campaign_views.xml",
        "views/lead_nurture_log_views.xml",
        "views/lead_nurture_rule_views.xml",
        "views/whatsapp_views.xml",
        "views/crm_lead_ext_views.xml",
        "views/lead_nurture_wizard_views.xml",
        "views/lead_nurture_menus.xml",
    ],
    "installable": True,
    "application": False,
}
