{
    "name": "Mumtaz Proposal Management",
    "summary": "Complete proposal/quotation lifecycle management under CRM",
    "version": "19.0.1.0.0",
    "category": "Sales/CRM",
    "author": "Mumtaz",
    "license": "LGPL-3",
    "depends": ["crm", "sale", "mail", "account"],
    "data": [
        "security/proposal_security.xml",
        "security/ir.model.access.csv",
        "data/proposal_sequence.xml",
        "data/proposal_cron.xml",
        "views/proposal_template_views.xml",
        "views/proposal_views.xml",
        "views/crm_lead_views.xml",
        "views/proposal_menus.xml",
        "wizards/proposal_send_views.xml",
        "report/proposal_report.xml",
        "report/proposal_report_template.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
