#!/usr/bin/env bash
# Generate nginx server blocks for all tenant custom domains.
#
# For each active tenant with a custom_domain set, this script creates a
# server block that proxies the domain to the tenant's Odoo database.
# Odoo is selected by appending ?db=<tenant_db> to the upstream path.
#
# Run this script whenever a tenant's custom domain changes:
#   - Manually:  sudo bash scripts/update-nginx-domains.sh
#   - Via cron:  */5 * * * * root /opt/Mumtaz/scripts/update-nginx-domains.sh
#
# Requirements:
#   - sqlite3 CLI installed
#   - nginx installed and running
#   - The tenant has already created a CNAME record pointing their domain → app.mumtaz.digital
#   - SSL: run 'certbot --nginx -d <domain>' once per new domain, or use a wildcard cert
set -euo pipefail

DB_PATH="${DB_PATH:-/opt/zaki-server/users.db}"
ODOO_UPSTREAM="${ODOO_UPSTREAM:-http://127.0.0.1:8069}"
CONF_OUT="/etc/nginx/conf.d/mumtaz-tenant-domains.conf"
ERPMATCH_PATHS="/ /web /web/ /odoo /odoo/"

# ── Require sqlite3 ───────────────────────────────────────────────────
if ! command -v sqlite3 >/dev/null 2>&1; then
    echo "ERROR: sqlite3 not found. Install with: apt-get install sqlite3" >&2
    exit 1
fi

# ── Fetch active tenant domains ───────────────────────────────────────
mapfile -t ROWS < <(
    sqlite3 "$DB_PATH" \
        "SELECT db_name || '|' || custom_domain
         FROM tenants
         WHERE status = 'active' AND custom_domain IS NOT NULL AND custom_domain != ''"
)

if [[ ${#ROWS[@]} -eq 0 ]]; then
    echo "No active tenant custom domains found."
    # Remove stale config if it exists
    if [[ -f "$CONF_OUT" ]]; then
        sudo rm -f "$CONF_OUT"
        sudo nginx -t && sudo systemctl reload nginx
        echo "Removed stale config $CONF_OUT"
    fi
    exit 0
fi

echo "Generating nginx config for ${#ROWS[@]} tenant domain(s)…"

# ── Build config ──────────────────────────────────────────────────────
{
cat <<'HEADER'
# Auto-generated by scripts/update-nginx-domains.sh — do not edit manually.
# Re-run the script to regenerate after domain changes.
HEADER

for row in "${ROWS[@]}"; do
    db_name="${row%%|*}"
    domain="${row##*|}"

    echo ""
    echo "# Tenant: $db_name → $domain"
    cat <<BLOCK
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    # Redirect HTTP → HTTPS (certbot will update this block with SSL)
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${domain};

    # SSL — run: certbot --nginx -d ${domain}
    # certbot will inject ssl_certificate lines here automatically.
    # Until then, this block will not serve HTTPS.

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options           "SAMEORIGIN"                          always;
    add_header X-Content-Type-Options    "nosniff"                             always;

    # Proxy all traffic to Odoo with the tenant DB pre-selected
    location / {
        proxy_pass         ${ODOO_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        # Tell Odoo which database to use
        proxy_set_header   X-Odoo-Dbfilter   "^${db_name}$";
        proxy_read_timeout 120s;
        proxy_buffering    off;

        # Rewrite requests that include ?db= to use the tenant DB
        # For Odoo longpolling
        proxy_set_header   Upgrade    \$http_upgrade;
        proxy_set_header   Connection "upgrade";
    }
}
BLOCK
done
} | sudo tee "$CONF_OUT" > /dev/null

# ── Test + reload nginx ───────────────────────────────────────────────
echo "Testing nginx config…"
if sudo nginx -t 2>&1; then
    sudo systemctl reload nginx
    echo "Done — nginx reloaded with ${#ROWS[@]} tenant domain(s)."
    echo ""
    echo "Next steps for each new domain:"
    echo "  1. Tenant must add a CNAME:  <domain>  →  app.mumtaz.digital"
    echo "  2. Once DNS propagates, issue SSL cert:"
    echo "     sudo certbot --nginx -d <domain>"
    echo "  3. Odoo must have dbfilter configured to allow tenant DB selection by header."
    echo "     Add to /etc/odoo/odoo.conf:   dbfilter = .*"
else
    echo "nginx config test FAILED — reverting"
    sudo rm -f "$CONF_OUT"
    exit 1
fi
