from . import faizy_plan
from . import faizy_subscription
from . import faizy_family_member
from . import faizy_worker
from . import faizy_application
from . import faizy_order
from . import faizy_request
from . import faizy_wallet
from . import faizy_whatsapp
from . import res_partner
